name: Dev to Test
on:
  workflow_dispatch
permissions:
  id-token: write
  contents: write
  checks: write
  pull-requests: write
jobs:
  open-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
    - name: install gh cli
      uses: ksivamuthu/actions-setup-gh-cli@v3
    - name: create pull request
      run: |
        pr_url="$(gh pr create -B test -H develop --title 'Merge develop into test' --body 'Created by Github action')"
        sleep 2
        gh pr merge --auto --merge "$pr_url"
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
